name: sadaqa_mobile_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ Localization (احترافي)
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2

  # تسجيل الدخول الاجتماعي
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.0

  # ✅ Stripe
  flutter_stripe: 10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # ✅ إضافة توليد أيقونة التطبيق
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # ✅ مهم جدًا لتوليد ملفات الترجمة تلقائيًا
  generate: true

  # ✅ (اختياري) لو لديك assets أخرى لاحقًا
  # assets:
  #   - assets/icon/app_icon.png

# ✅ إعدادات تغيير الأيقونة (خارج flutter:)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpeg"
  min_sdk_android: 21







# name: sadaqa_mobile_app
# description: "A new Flutter project."
# publish_to: "none"

# version: 1.0.0+1

# environment:
#   sdk: ">=3.5.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter

#   # ✅ Localization (احترافي)
#   flutter_localizations:
#     sdk: flutter
#   intl: ^0.20.2

#   cupertino_icons: ^1.0.8
#   http: ^1.2.2
#   shared_preferences: ^2.3.2

#   # تسجيل الدخول الاجتماعي
#   google_sign_in: ^6.2.1
#   flutter_facebook_auth: ^7.1.0

#   # ✅ Stripe
#   flutter_stripe: 10.1.1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^4.0.0

# flutter:
#   uses-material-design: true

#   # ✅ مهم جدًا لتوليد ملفات الترجمة تلقائيًا
#   generate: true
